export enum EventStatus {
  AVAILABLE = 'AVAILABLE',
  NOT_AVAILABLE = 'NOT_AVAILABLE',
  CANCELLED = 'CANCELLED',
  FREE = 'FREE',
}

export enum Role {
  REGULAR_USER = 'REGULAR_USER',
  EVENT_PLANNER = 'EVENT_PLANNER',
  ADMIN = 'ADMIN',
}

export enum TicketType {
  EARLY_BIRD = 'EARLY_BIRD',
  REGULAR = 'REGULAR',
  VIP = 'VIP',
  VVIP = 'VVIP',
  GENERAL_ADMISSION = 'GENERAL_ADMISSION',
  STAGE_ACCESS = 'STAGE_ACCESS',
  STUDENT_DISCOUNT = 'STUDENT_DISCOUNT',
  GROUP_OF_5 = 'GROUP_OF_5',
  GROUP_OF_10 = 'GROUP_OF_10',
  LIVE_STREAM_ACCESS = 'LIVE_STREAM_ACCESS',
  FREE_TICKET = 'FREE_TICKET',
}
