export enum EventStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  CABCELLED = 'CANCELLED',
}

export enum Role {
  REGULAR_USER = 'REGULAR_USER',
  EVENT_PLANNER = 'EVENT_PLANNER',
  ADMIN = 'ADMIN',
}
